### ISSUE TITLE
Erreur dans les tests d'exemples

### ISSUE THREAD

**Issue by Thibaud-DT** [tclavier/jersey-skeleton#2]
Bonjour,
une petite erreur c'est glissée dans les tests d'exemples.

Fichier : RestClientTest.java
Erreur ligne 31

```
String baseUrl = this.getBaseUri() + "/userdb/";
```

L'erreur provient selon moi d'un slash de trop.

```
String baseUrl = this.getBaseUri() + "userdb";
```

**Comment by tclavier** [comment]
Pull request ?
