### ISSUE TITLE
Driver sqlite buggé sous linux

### ISSUE THREAD

**Issue by ghost** [tclavier/jersey-skeleton#5]
Le driver jdbc sqlite présent dans le pom est buggé sous Linux (issue sur le repository de sqlite-jdbc : https://bitbucket.org/xerial/sqlite-jdbc/issues/152/387-version-linux-issue). Si on l'utilise, on obtient une erreur à la connexion (UnsatisfiedLinkError).

Pourriez-vous mettre à jour le pom pour utiliser une version stable sous tous les OS ?

**Comment by tclavier** [comment]
D'après le lien c'est la version 3.7.2 or nous utilisons la version 3.8.7, je met à jour quand même vers la dernière version 3.8.11.2
